[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["kevingzhang <kevin.zhang.canada@gmail.com>"]
edition = "2018"


[lib]
crate-type = ['cdylib']

[dependencies]
hello-shared = {path = "../hello-shared"}
binio-wasm = { path ="../../binio-wasm"}